# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

cache: packages

# Bioconductor
bioc_required: true

# On CRAN all warnings are treated as errors; this is not true on Bioconductor.
warnings_are_errors: false

# Need this if also using covr to get code coverage
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
